language: groovy
branches:
  only:
  - master
script: "./grailsw test-app"
addons:
  ssh_known_hosts: 
before_deploy:
- openssl aes-256-cbc -K $encrypted_0507f37990af_key -iv $encrypted_0507f37990af_iv
  -in travis_deploy.enc -out /tmp/travis_deploy -d - eval "$(ssh-agent -s)" - chmod
  600 /tmp/travis_deploy - ssh-add /tmp/travis_deploy
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/* nquire@nquire.andreassen.info:/home/nquire/test
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_01d828e8bf7c_key -iv $encrypted_01d828e8bf7c_iv
  -in travis_deploy.enc -out travis_deploy -d
