language: groovy
branches:
  only:
  - master
script: "./grailsw test-app"
before_install:
- openssl aes-256-cbc -K $encrypted_0507f37990af_key -iv $encrypted_0507f37990af_iv
  -in travis_deploy.enc -out travis_deploy -d
