language: groovy
branches:
  only:
  - master
script: "./grailsw test-app"
addons:
  ssh_known_hosts: nquire.andreassen.info
before_deploy:
  - openssl aes-256-cbc -K $encrypted_01d828e8bf7c_key -iv $encrypted_01d828e8bf7c_iv -in travis_deploy.enc -out /tmp/travis_deploy -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/travis_deploy
  - ssh-add /tmp/travis_deploy
deploy:
- provider: script
  skip_cleanup: true
  #script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/* nquire@nquire.andreassen.info:/home/nquire/test
  script: scp $TRAVIS_BUILD_DIR/build/libs/nquire.war nquire@nquire.andreassen.info:/home/nquire/deploy_temp/
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: ssh nquire@nquire.andreassen.info 'sudo /home/nquire/deploy_temp/deploy'
  on:
    branch: master
